import { TestCaseInfo } from "./test-runner.types";

// ─── Shared message block lengths (mirrors scripts/test-ai-concierge.ts) ─────
// P0=3, identity=2, clinic=1 or 2, emb=1 or 3, egg=1, sperm=1, carrier=1, surr=1
// surrogateMatch=4, agencyMatch=2, eggDonorMatch=2, spermDonorMatch=3, clinicMatch=6

export interface TestCaseDef {
  id: string;
  persona: string;
  name: string;
  desc: string;
  interestedServices: string[];
  messageCount: number;
}

export const TEST_CASES: TestCaseDef[] = [
  // ── SOLO MAN (SM-01 to SM-14) ─────────────────────────────────────────────
  {
    id: "SM-01", persona: "solo-man",
    name: "SM-01: No embryos - Own sperm - Needs all services - Intake only",
    desc: "Most common solo man path - validates intake: no carrier Q, no egg source Q, sperm Q asked",
    interestedServices: ["Surrogate", "Egg Donor", "Fertility Clinic"],
    messageCount: 10,
  },
  {
    id: "SM-02", persona: "solo-man",
    name: "SM-02: No embryos - Own sperm - Has egg donor - CLINIC_HAVE - USA - Pro-life - Twins",
    desc: "CLINIC_HAVE: egg donor skipped, D-cycle validates pro-life + twins preferences saved",
    interestedServices: ["Surrogate"],
    messageCount: 14,
  },
  {
    id: "SM-03", persona: "solo-man",
    name: "SM-03: No embryos - Own sperm - Already has surrogate - CLINIC_HAVE - Egg donor match",
    desc: "CLINIC_HAVE: Step 2 egg source SKIPPED for solo man. Sperm then has surrogate",
    interestedServices: ["Egg Donor"],
    messageCount: 9,
  },
  {
    id: "SM-04", persona: "solo-man",
    name: "SM-04: No embryos - Donor sperm - All services - Intake only",
    desc: "Validates donor sperm path + sperm donor help Q asked, no carrier Q",
    interestedServices: ["Surrogate", "Egg Donor", "Sperm Donor", "Fertility Clinic"],
    messageCount: 11,
  },
  {
    id: "SM-05", persona: "solo-man",
    name: "SM-05: No embryos - Donor sperm - Has sperm donor - CLINIC_HAVE - Colombia",
    desc: "CLINIC_HAVE: sperm donor skipped, egg donor then Colombia agency",
    interestedServices: ["Surrogate", "Egg Donor"],
    messageCount: 13,
  },
  {
    id: "SM-06", persona: "solo-man",
    name: "SM-06: No embryos - Donor sperm - CLINIC_HAVE - Mexico",
    desc: "CLINIC_HAVE: Mexico agency match (D2 termination skipped for international)",
    interestedServices: ["Surrogate", "Egg Donor", "Sperm Donor"],
    messageCount: 13,
  },
  {
    id: "SM-07", persona: "solo-man",
    name: "SM-07: No embryos - Own sperm - CLINIC_HAVE - Mixed USA + Colombia",
    desc: "CLINIC_HAVE: Path C mixed countries intake - validates D1 accepts multi-country",
    interestedServices: ["Surrogate", "Egg Donor"],
    messageCount: 14,
  },
  {
    id: "SM-08", persona: "solo-man",
    name: "SM-08: Has embryos (2, tested) - Own sperm - Has egg donor - CLINIC_HAVE - USA",
    desc: "CLINIC_HAVE: existing embryos, D-cycle validates USA singleton preferences",
    interestedServices: ["Surrogate"],
    messageCount: 15,
  },
  {
    id: "SM-09", persona: "solo-man",
    name: "SM-09: Has embryos (1, not tested) - CLINIC_HAVE - Colombia",
    desc: "CLINIC_HAVE: ships embryos to Colombia, D-cycle runs",
    interestedServices: ["Surrogate"],
    messageCount: 14,
  },
  {
    id: "SM-10", persona: "solo-man",
    name: "SM-10: Has embryos - Step 3b use existing - Intake only",
    desc: "Step 3b conflict: validates sperm conflict USE branch",
    interestedServices: ["Surrogate", "Sperm Donor", "Fertility Clinic"],
    messageCount: 11,
  },
  {
    id: "SM-11", persona: "solo-man",
    name: "SM-11: Has embryos - Step 3b create new embryos - Intake only",
    desc: "Step 3b conflict: creates new embryos - validates Step 3b create branch",
    interestedServices: ["Surrogate", "Egg Donor", "Sperm Donor", "Fertility Clinic"],
    messageCount: 13,
  },
  {
    id: "SM-12", persona: "solo-man",
    name: "SM-12: No embryos - Own sperm - CLINIC_HAVE - USA - Cost education check",
    desc: "CLINIC_HAVE: D-cycle checks cost education",
    interestedServices: ["Surrogate", "Egg Donor"],
    messageCount: 14,
  },
  {
    id: "SM-13", persona: "solo-man",
    name: "SM-13: LGBTQ+ - No embryos - Own sperm - CLINIC_HAVE - USA - Twins",
    desc: "Gay solo man - CLINIC_HAVE: isLGBTQ=true saved, D-cycle includes twins pref",
    interestedServices: ["Surrogate", "Egg Donor"],
    messageCount: 14,
  },
  {
    id: "SM-14", persona: "solo-man",
    name: "SM-14: No embryos - Donor sperm - CLINIC_HAVE - Colombia",
    desc: "CLINIC_HAVE: clinic already set, Colombia agency match runs",
    interestedServices: ["Surrogate", "Egg Donor", "Sperm Donor"],
    messageCount: 13,
  },

  // ── SOLO WOMAN (SW-01 to SW-14) ───────────────────────────────────────────
  {
    id: "SW-01", persona: "solo-woman",
    name: "SW-01: No embryos - Own eggs - Self carry - Needs sperm donor - Has clinic",
    desc: "Simplest solo woman path - IUI/IVF with own eggs, self-carry, sperm donor",
    interestedServices: ["Sperm Donor"],
    messageCount: 14,
  },
  {
    id: "SW-02", persona: "solo-woman",
    name: "SW-02: No embryos - Own eggs - Self carry - Already has sperm donor - Needs clinic",
    desc: "Solo woman already has sperm donor - sperm match cycle entirely skipped",
    interestedServices: ["Fertility Clinic"],
    messageCount: 13,
  },
  {
    id: "SW-03", persona: "solo-woman",
    name: "SW-03: No embryos - Donor eggs - Self carry - Needs egg donor + sperm donor - Has clinic",
    desc: "Embryo donation - solo woman with donor eggs and donor sperm, self-carry",
    interestedServices: ["Egg Donor", "Sperm Donor"],
    messageCount: 16,
  },
  {
    id: "SW-04", persona: "solo-woman",
    name: "SW-04: No embryos - Donor eggs - Already has egg donor - Self carry - Needs sperm donor - Needs clinic",
    desc: "Solo woman already has egg donor - egg match cycle skipped",
    interestedServices: ["Sperm Donor"],
    messageCount: 16,
  },
  {
    id: "SW-05", persona: "solo-woman",
    name: "SW-05: No embryos - Own eggs - Surrogate - Needs surrogate + sperm donor + clinic - USA",
    desc: "Solo woman with surrogate - all services needed",
    interestedServices: ["Surrogate", "Sperm Donor", "Fertility Clinic"],
    messageCount: 24,
  },
  {
    id: "SW-06", persona: "solo-woman",
    name: "SW-06: No embryos - Own eggs - Already has surrogate - Needs sperm donor - Needs clinic",
    desc: "Solo woman already has surrogate - surrogate Phase 3 entirely skipped",
    interestedServices: ["Sperm Donor"],
    messageCount: 18,
  },
  {
    id: "SW-07", persona: "solo-woman",
    name: "SW-07: No embryos - Donor eggs - Surrogate - Needs all three - USA - Pro-choice - Twins",
    desc: "Solo woman full embryo donation + surrogate - all services run",
    interestedServices: ["Surrogate", "Egg Donor", "Sperm Donor"],
    messageCount: 21,
  },
  {
    id: "SW-08", persona: "solo-woman",
    name: "SW-08: No embryos - Donor eggs - Surrogate - All services - Colombia",
    desc: "Solo woman Colombia path - agency search instead of individual surrogate",
    interestedServices: ["Surrogate", "Egg Donor", "Sperm Donor"],
    messageCount: 24,
  },
  {
    id: "SW-09", persona: "solo-woman",
    name: "SW-09: Has embryos (2, tested) - Own eggs - Self carry - Has clinic",
    desc: "Solo woman with existing tested embryos, self-carry - past-tense questions",
    interestedServices: [],
    messageCount: 15,
  },
  {
    id: "SW-10", persona: "solo-woman",
    name: "SW-10: Has embryos - Step 1c fires - Uses existing - Surrogate - USA - Pro-life",
    desc: "Step 1c: registered for egg donation but has embryos - uses existing embryos",
    interestedServices: ["Surrogate", "Egg Donor"],
    messageCount: 21,
  },
  {
    id: "SW-11", persona: "solo-woman",
    name: "SW-11: Has embryos - Step 1c create new embryos - Surrogate - USA",
    desc: "Step 1c: creates new embryos with fresh egg donor, needs surrogate",
    interestedServices: ["Surrogate", "Egg Donor"],
    messageCount: 19,
  },
  {
    id: "SW-12", persona: "solo-woman",
    name: "SW-12: No embryos - Own eggs - Surrogate - USA - No preference",
    desc: "Solo woman verifying no-preference answers on D2 and D3",
    interestedServices: ["Surrogate", "Sperm Donor"],
    messageCount: 20,
  },
  {
    id: "SW-13", persona: "solo-woman",
    name: "SW-13: No embryos - Donor eggs - Surrogate - Mexico",
    desc: "Solo woman Mexico path - international agency card, D2 termination skipped",
    interestedServices: ["Surrogate", "Egg Donor", "Sperm Donor"],
    messageCount: 17,
  },
  {
    id: "SW-14", persona: "solo-woman",
    name: "SW-14: LGBTQ+ - No embryos - Own eggs - Self carry - Sperm donor - Needs clinic",
    desc: "LGBTQ+ solo woman - isLGBTQ saved, otherwise same flow",
    interestedServices: ["Sperm Donor"],
    messageCount: 16,
  },

  // ── TWO DADS (TD-01 to TD-12) ─────────────────────────────────────────────
  {
    id: "TD-01", persona: "two-dads",
    name: "TD-01: No embryos - My own sperm - Needs egg donor + surrogate - Has clinic - USA",
    desc: "Base two-dads path - own sperm, USA surrogate",
    interestedServices: ["Surrogate", "Egg Donor"],
    messageCount: 17,
  },
  {
    id: "TD-02", persona: "two-dads",
    name: "TD-02: No embryos - Partner's sperm - Needs all - USA - Pro-choice - Twins",
    desc: "Two dads with partner's sperm - verifies partner's sperm option available",
    interestedServices: ["Surrogate", "Egg Donor"],
    messageCount: 23,
  },
  {
    id: "TD-03", persona: "two-dads",
    name: "TD-03: No embryos - Donor sperm - All services - USA - Pro-choice - Singleton",
    desc: "Two dads embryo donation - all donor, all services",
    interestedServices: ["Surrogate", "Egg Donor", "Sperm Donor"],
    messageCount: 20,
  },
  {
    id: "TD-04", persona: "two-dads",
    name: "TD-04: No embryos - Donor sperm - Already has sperm donor - Needs egg donor + surrogate - Colombia",
    desc: "Two dads already have sperm donor - sperm match skipped, Colombia international",
    interestedServices: ["Surrogate", "Egg Donor"],
    messageCount: 17,
  },
  {
    id: "TD-05", persona: "two-dads",
    name: "TD-05: No embryos - My own sperm - Already has egg donor - USA - Pro-life",
    desc: "Two dads with existing egg donor - egg match skipped, pro-life surrogate",
    interestedServices: ["Surrogate"],
    messageCount: 20,
  },
  {
    id: "TD-06", persona: "two-dads",
    name: "TD-06: No embryos - My own sperm - Needs egg donor - Already has surrogate",
    desc: "Two dads already have surrogate - Phase 3 D-cycle skipped entirely",
    interestedServices: ["Egg Donor"],
    messageCount: 17,
  },
  {
    id: "TD-07", persona: "two-dads",
    name: "TD-07: Has embryos (2, tested) - My own sperm - Needs surrogate - USA",
    desc: "Two dads with existing tested embryos - past-tense sperm question",
    interestedServices: ["Surrogate"],
    messageCount: 21,
  },
  {
    id: "TD-08", persona: "two-dads",
    name: "TD-08: Has embryos (3) - Partner's sperm - Needs surrogate - Colombia",
    desc: "Two dads ship existing embryos with partner's sperm to Colombia",
    interestedServices: ["Surrogate"],
    messageCount: 13,
  },
  {
    id: "TD-09", persona: "two-dads",
    name: "TD-09: Has embryos - Registered sperm donor - Step 3b use existing",
    desc: "Step 3b conflict for two dads - chooses to use existing embryos",
    interestedServices: ["Surrogate", "Sperm Donor"],
    messageCount: 20,
  },
  {
    id: "TD-10", persona: "two-dads",
    name: "TD-10: No embryos - Partner's sperm - Needs egg donor + surrogate - Mexico",
    desc: "Two dads Mexico international path with partner's sperm",
    interestedServices: ["Surrogate", "Egg Donor"],
    messageCount: 15,
  },
  {
    id: "TD-11", persona: "two-dads",
    name: "TD-11: No embryos - My own sperm - Mixed USA + Colombia - Twins",
    desc: "Two dads Path C mixed countries with twins preference",
    interestedServices: ["Surrogate", "Egg Donor"],
    messageCount: 20,
  },
  {
    id: "TD-12", persona: "two-dads",
    name: "TD-12: No embryos - Donor sperm - All services - USA - No preference",
    desc: "Two dads embryo donation with all no-preference answers",
    interestedServices: ["Surrogate", "Egg Donor", "Sperm Donor"],
    messageCount: 23,
  },

  // ── TWO MOMS (TM-01 to TM-13) ─────────────────────────────────────────────
  {
    id: "TM-01", persona: "two-moms",
    name: "TM-01: No embryos - Partner A eggs - Partner A carries - Needs sperm donor - Needs clinic",
    desc: "Simplest two-moms path: same person provides eggs and carries",
    interestedServices: ["Sperm Donor"],
    messageCount: 18,
  },
  {
    id: "TM-02", persona: "two-moms",
    name: "TM-02: No embryos - Partner A eggs - Partner A carries - Already has sperm donor - Needs clinic",
    desc: "Two moms already have sperm donor - sperm match cycle skipped",
    interestedServices: [],
    messageCount: 15,
  },
  {
    id: "TM-03", persona: "two-moms",
    name: "TM-03: No embryos - Partner B eggs - Partner A carries (Reciprocal IVF) - Needs sperm donor + clinic",
    desc: "Reciprocal IVF: Partner A carries, Partner B provides eggs",
    interestedServices: ["Sperm Donor"],
    messageCount: 18,
  },
  {
    id: "TM-04", persona: "two-moms",
    name: "TM-04: No embryos - Donor eggs - Partner A carries - Needs egg donor + sperm donor + clinic",
    desc: "Two moms with third-party egg donor, self-carry - embryo donation path",
    interestedServices: ["Egg Donor", "Sperm Donor"],
    messageCount: 21,
  },
  {
    id: "TM-05", persona: "two-moms",
    name: "TM-05: No embryos - Donor eggs - Already has egg donor - Partner A carries - Needs sperm donor",
    desc: "Two moms already have egg donor - egg match skipped",
    interestedServices: ["Sperm Donor"],
    messageCount: 14,
  },
  {
    id: "TM-06", persona: "two-moms",
    name: "TM-06: No embryos - Partner A eggs - Partner B carries - Needs sperm donor + clinic",
    desc: "Partner B carries with Partner A's eggs - carrier = My partner",
    interestedServices: ["Sperm Donor"],
    messageCount: 18,
  },
  {
    id: "TM-07", persona: "two-moms",
    name: "TM-07: No embryos - Partner B eggs - Partner B carries (both) - Needs sperm donor + clinic",
    desc: "Partner B provides eggs AND carries - full partner path",
    interestedServices: ["Sperm Donor"],
    messageCount: 18,
  },
  {
    id: "TM-08", persona: "two-moms",
    name: "TM-08: No embryos - Partner A eggs - Surrogate carries - Needs surrogate + sperm donor + clinic",
    desc: "Two moms using surrogate with own eggs",
    interestedServices: ["Surrogate", "Sperm Donor"],
    messageCount: 25,
  },
  {
    id: "TM-09", persona: "two-moms",
    name: "TM-09: No embryos - Donor eggs - Surrogate carries - All services - USA - Twins",
    desc: "Two moms all-donor + surrogate with twins preference",
    interestedServices: ["Surrogate", "Egg Donor", "Sperm Donor"],
    messageCount: 22,
  },
  {
    id: "TM-10", persona: "two-moms",
    name: "TM-10: No embryos - Partner B eggs - Surrogate carries - Colombia - Needs sperm donor",
    desc: "Two moms reciprocal IVF eggs + surrogate + Colombia",
    interestedServices: ["Surrogate", "Sperm Donor"],
    messageCount: 17,
  },
  {
    id: "TM-11", persona: "two-moms",
    name: "TM-11: Has embryos (2, tested) - Partner A eggs - Partner B carries - Has clinic",
    desc: "Two moms with existing tested embryos, partner carries - Phase 2 validation only (no match cycle)",
    interestedServices: [],
    messageCount: 12,
  },
  {
    id: "TM-12", persona: "two-moms",
    name: "TM-12: Has embryos - Step 1c fires - Uses existing - Surrogate - USA",
    desc: "Step 1c for two moms: registered for egg donation + has embryos - use existing",
    interestedServices: ["Surrogate", "Egg Donor"],
    messageCount: 22,
  },
  {
    id: "TM-13", persona: "two-moms",
    name: "TM-13: No embryos - Donor eggs - Surrogate carries - Already has surrogate - Needs sperm donor + clinic",
    desc: "Two moms already have surrogate - Phase 3 D-cycle skipped",
    interestedServices: ["Egg Donor", "Sperm Donor"],
    messageCount: 22,
  },

  // ── MAN & WOMAN (MW-01 to MW-19) ──────────────────────────────────────────
  {
    id: "MW-01", persona: "man-woman",
    name: "MW-01: No embryos - Her eggs - His sperm - She carries - Needs clinic (Woman speaking)",
    desc: "Simplest MW path - own genetics, self-carry, clinic only",
    interestedServices: [],
    messageCount: 15,
  },
  {
    id: "MW-02", persona: "man-woman",
    name: "MW-02: No embryos - Her eggs - His sperm - She carries - Needs clinic (Man speaking)",
    desc: "Same biology as MW-01 but man is speaking - verifies correct option framing",
    interestedServices: [],
    messageCount: 15,
  },
  {
    id: "MW-03", persona: "man-woman",
    name: "MW-03: No embryos - Donor eggs - His sperm - She carries - Needs egg donor + clinic (Woman speaking)",
    desc: "MW couple with donor eggs, self-carry",
    interestedServices: ["Egg Donor"],
    messageCount: 19,
  },
  {
    id: "MW-04", persona: "man-woman",
    name: "MW-04: No embryos - Donor eggs - His sperm - She carries - Already has egg donor - Needs clinic (Man speaking)",
    desc: "Already has egg donor - egg match skipped, man speaking",
    interestedServices: [],
    messageCount: 14,
  },
  {
    id: "MW-05", persona: "man-woman",
    name: "MW-05: No embryos - Her eggs - Donor sperm - She carries - Needs sperm donor + clinic (Woman speaking)",
    desc: "MW couple with donor sperm, her own eggs, self-carry",
    interestedServices: ["Sperm Donor"],
    messageCount: 19,
  },
  {
    id: "MW-06", persona: "man-woman",
    name: "MW-06: No embryos - Her eggs - Donor sperm - She carries - Already has sperm donor - Has clinic (Man speaking)",
    desc: "Already has sperm donor + clinic - no match cycles at all",
    interestedServices: [],
    messageCount: 11,
  },
  {
    id: "MW-07", persona: "man-woman",
    name: "MW-07: No embryos - Donor eggs - Donor sperm - She carries - All services (Woman speaking)",
    desc: "Full embryo donation, self-carry for MW couple",
    interestedServices: ["Egg Donor", "Sperm Donor"],
    messageCount: 22,
  },
  {
    id: "MW-08", persona: "man-woman",
    name: "MW-08: No embryos - Her eggs - His sperm - Surrogate carries - USA - Pro-choice (Woman speaking)",
    desc: "MW couple own genetics with surrogate",
    interestedServices: ["Surrogate"],
    messageCount: 21,
  },
  {
    id: "MW-09", persona: "man-woman",
    name: "MW-09: No embryos - Her eggs - His sperm - Surrogate carries - USA - Twins - Has clinic (Man speaking)",
    desc: "MW couple with surrogate + twins, man speaking",
    interestedServices: ["Surrogate"],
    messageCount: 16,
  },
  {
    id: "MW-10", persona: "man-woman",
    name: "MW-10: No embryos - Donor eggs - His sperm - Surrogate carries - Needs egg + surrogate + clinic - USA (Woman speaking)",
    desc: "MW couple donor eggs with surrogate, no preference answers",
    interestedServices: ["Surrogate", "Egg Donor"],
    messageCount: 23,
  },
  {
    id: "MW-11", persona: "man-woman",
    name: "MW-11: No embryos - Her eggs - Donor sperm - Already has surrogate - Needs sperm donor + clinic (Woman speaking)",
    desc: "MW couple already has surrogate - Phase 3 D-cycle skipped",
    interestedServices: ["Sperm Donor"],
    messageCount: 20,
  },
  {
    id: "MW-12", persona: "man-woman",
    name: "MW-12: No embryos - Donor eggs - Donor sperm - Surrogate - All services - USA - Pro-life (Man speaking)",
    desc: "All-donor + surrogate for MW couple, pro-life termination, man speaking",
    interestedServices: ["Surrogate", "Egg Donor", "Sperm Donor"],
    messageCount: 26,
  },
  {
    id: "MW-13", persona: "man-woman",
    name: "MW-13: No embryos - Donor eggs - Donor sperm - Surrogate - Colombia (Woman speaking)",
    desc: "MW couple Colombia international path - all donor services",
    interestedServices: ["Surrogate", "Egg Donor", "Sperm Donor"],
    messageCount: 23,
  },
  {
    id: "MW-14", persona: "man-woman",
    name: "MW-14: Has embryos (2, tested) - Her eggs - His sperm - She carries - Needs clinic (Woman speaking)",
    desc: "MW couple with existing tested embryos, self-carry - past-tense questions, clinic only",
    interestedServices: [],
    messageCount: 17,
  },
  {
    id: "MW-15", persona: "man-woman",
    name: "MW-15: Has embryos (4, tested) - Her eggs - His sperm - Surrogate carries - USA (Man speaking)",
    desc: "MW couple with existing embryos, using surrogate, man speaking",
    interestedServices: ["Surrogate"],
    messageCount: 24,
  },
  {
    id: "MW-16", persona: "man-woman",
    name: "MW-16: Has embryos - Step 1c fires - Use existing embryos - She carries - Needs clinic (Woman speaking)",
    desc: "Step 1c for MW: registered for egg donation + has embryos - uses existing",
    interestedServices: ["Egg Donor"],
    messageCount: 16,
  },
  {
    id: "MW-17", persona: "man-woman",
    name: "MW-17: Has embryos - Step 1c create new embryos - Surrogate - USA (Woman speaking)",
    desc: "Step 1c MW: creates new embryos with fresh donor, uses surrogate",
    interestedServices: ["Surrogate", "Egg Donor"],
    messageCount: 22,
  },
  {
    id: "MW-18", persona: "man-woman",
    name: "MW-18: Has embryos - Step 3b fires - Use existing - She carries - Needs clinic (Woman speaking)",
    desc: "Step 3b MW: registered for sperm donation + has embryos - use existing",
    interestedServices: ["Sperm Donor"],
    messageCount: 16,
  },
  {
    id: "MW-19", persona: "man-woman",
    name: "MW-19: No embryos - Donor eggs - His sperm - Surrogate carries - Mexico (Man speaking)",
    desc: "MW couple Mexico international path, man speaking",
    interestedServices: ["Surrogate", "Egg Donor"],
    messageCount: 22,
  },

  // ── FREE-TEXT REQUEST HANDLING (FT-01 to FT-04) ──────────────────────────
  // Runs scripts/test-freetext-requests.ts (off-script behavior the scripted
  // decision-tree cases above cannot reach). See docs/freetext-request-test-plan.md.
  {
    id: "FT-01", persona: "free-text",
    name: "FT-01: Deep-link surrogate pin - schedule a call / service switches / same-service ask",
    desc: "Marketplace pin 4-turn replay: calendar renders, egg/sperm/surrogate free-text asks engaged, streams on-topic, coherent QRs",
    interestedServices: ["Surrogate"],
    messageCount: 4,
  },
  {
    id: "FT-02", persona: "free-text",
    name: "FT-02: Confirm-never-overrule - embryos on file, donor requested",
    desc: "45 PGT-A embryos saved + egg/sperm donor ask -> confirm question with its own QRs, no refusal, no directive leak",
    interestedServices: ["Surrogate"],
    messageCount: 2,
  },
  {
    id: "FT-03", persona: "free-text",
    name: "FT-03: Sperm C2 - donor-type answer saved, never re-asked",
    desc: "'Open' answer patched to spermDonorType via C2 SAVE FALLBACK; question never repeats",
    interestedServices: ["Sperm Donor"],
    messageCount: 4,
  },
  {
    id: "FT-04", persona: "free-text",
    name: "FT-04: Buy vials - purchase intent ends in checkout",
    desc: "'Buy vials now' -> short confirmation + bank_checkout card (or agency guidance), never a re-presented match card",
    interestedServices: ["Sperm Donor"],
    messageCount: 5,
  },
];

export function getTestCaseInfo(): TestCaseInfo[] {
  return TEST_CASES.map(tc => ({
    id: tc.id,
    persona: tc.persona,
    name: tc.name,
    desc: tc.desc,
    interestedServices: tc.interestedServices,
    messageCount: tc.messageCount,
  }));
}
