-- Cached human-readable digests of knowledge sources (website / documents),
-- generated by Gemini from the raw KnowledgeChunk text.
CREATE TABLE IF NOT EXISTS "KnowledgeDigest" (
  "id" TEXT NOT NULL,
  "digestKey" TEXT NOT NULL,
  "providerId" TEXT,
  "sourceType" TEXT NOT NULL,
  "sourceFileName" TEXT,
  "content" TEXT NOT NULL,
  "chunkCount" INTEGER NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "KnowledgeDigest_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "KnowledgeDigest_digestKey_key" ON "KnowledgeDigest"("digestKey");
CREATE INDEX IF NOT EXISTS "KnowledgeDigest_providerId_idx" ON "KnowledgeDigest"("providerId");

-- Deny-all RLS like every public table (blocks PostgREST; Prisma connects as owner).
ALTER TABLE "KnowledgeDigest" ENABLE ROW LEVEL SECURITY;
